# See http://www.appveyor.com/docs/appveyor-yml for many more options
install:
  - cinst pester
build: false
test_script:
# Test with native PS version
  - ps: . .\Tests\appveyor.pester.ps1
# Finalize pass - collect and upload results
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize
# Notify Slack Channel
notifications:
  - provider: Slack
    incoming_webhook:
      secure: KZIBT1mQ9haiVMAWAMGDKBafVzZc2HT886BPd9hF7IjspFRFeI90d/tlkyXCc7lFDH127pcvKHmrx8zSdqqfJjurMfdErxGU3oqdI6MtQM4=
